baseURL = "https://fpt-challengers-group2.github.io/Cloud-Sentinel/"
relativeURLs = true
canonifyURLs = true

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "tranphuonghuyen2005@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "Proposal Report"
weight = 1
languageName = "English"


[Languages.vi]
title = "Báo cáo đề án thực tập"
weight = 2
languageName = "Tiếng Việt"

[[languages.en.menu.shortcut]]
  name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
  url = "https://awsstudygroup.com"
  weight = 1

[[languages.en.menu.shortcut]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
  url = "https://www.facebook.com/groups/awsstudygroupfcj"
  weight = 2

[[languages.vi.menu.shortcut]]
  name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
  url = "https://awsstudygroup.com"
  weight = 1

[[languages.vi.menu.shortcut]]
  name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
  url = "https://www.facebook.com/groups/awsstudygroupfcj"
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
